feat: added last-update date to files card inside bando
RedTurtle/io-sanita-theme pull request #37
Opened 2024-09-16 10:19 UTC by Wagner3UB

Aggiunto la data di ultima modifica per i file dentro ad un bando. Prop "showModified" aggiunta per limitare la visualizzazione dentro i card.

<img width="820" alt="Schermata 2024-09-16 alle 12 15 25" src="https://github.com/user-attachments/assets/ca75bf59-97c5-40ee-b980-d9e1fc5e5abe">

2024-09-18 08:28 UTC, giuliaghisini commented on src/components/Cards/CardFile/CardFile.jsx
> +          {showModified && item?.modified && item?.['@type'] === 'File' && (
```suggestion
          {showModified && item?.modified && (
```

2024-09-18 08:28 UTC, giuliaghisini commented on src/components/Cards/CardFile/CardFile.jsx
> +    id: 'last_update',
```suggestion
    id: 'card_file_last_update',
```

2024-09-18 09:55 UTC, Wagner3UB commented on src/components/Cards/CardFile/CardFile.jsx
> +          {showModified && item?.modified && item?.['@type'] === 'File' && (
@giuliaghisini  senza questo il card ci fa vedere la data per qualsiasi contenuto, è voluto? Chiedo per certezza.

2024-09-18 10:05 UTC, Wagner3UB commented on src/components/Cards/CardFile/CardFile.jsx
> +          {showModified && item?.modified && item?.['@type'] === 'File' && (
Si vedono sui collegamenti, per esempio

2024-09-18 10:21 UTC, giuliaghisini commented on src/components/Cards/CardFile/CardFile.jsx
> +          {showModified && item?.modified && item?.['@type'] === 'File' && (
si vuole vederli anche nei moduli, l'idea era quella
quindi: rimetti la condizione che avevi messo tu e gestisci la data anche nel componente del modulo che viene usato all'inizio della return

2024-09-19 07:36 UTC, giuliaghisini requested changes

2024-09-19 07:36 UTC, giuliaghisini commented on src/components/Cards/CardFile/Module.jsx
> +  console.log(modulo);
```suggestion

```

2024-09-19 07:37 UTC, giuliaghisini commented
@Wagner3UB risolvi i conflitti e poi lo mergiamo

2024-09-19 08:56 UTC, merged